site_name: EMR Best Practices Guides
repo_name: "aws/aws-emr-best-practices"
repo_url: "https://github.com/aws/aws-emr-best-practices"
docs_dir: "content"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Introduction: 'index.md'
  - 1 - Cost Optimizations:
    - Introduction: 'cost_optimization/introduction.md'
    - Best Practices: 'cost_optimization/best_practices.md'
  - 2 - Reliability:
    - Introduction: 'reliability/introduction.md'
    - Best Practices: 'reliability/best_practices.md'   
  - 3 - Security: 
    - Introduction: 'security/introduction.md'
    - Best Practices: 'security/best_practices.md'    
  - 4 - Features: 
    - 4.1 - Managed Scaling: 'features/managed_scaling/best_practices.md'     
    - 4.2 - Spot Usage: 'features/spot_usage/best_practices.md'              
  # - 4 - Performance Efficiency: 'index.md'
  # - 5 - Operational Excellence: 'index.md'
  - 5 - Applications:
      - 5.1 Spark:
        - Introduction: 'applications/spark/introduction.md'
        - Best Practices: 'applications/spark/best_practices.md'
      - 5.2 Hive:
        - Introduction: 'applications/hive/introduction.md'
        - Best Practices: 'applications/hive/best_practices.md'
      - 5.3 HBase:
        - Introduction: 'applications/hbase/introduction.md'
        - Best Practice: 'applications/hbase/best_practice.md'
        - Best Practice for HDFS: 'applications/hbase/best_practice_hdfs.md'
        - Best Practice for Amazon S3: 'applications/hbase/best_practice_s3.md'
        - Data Integrity: 'applications/hbase/data_integrity.md'        
        - Data Migration: 'applications/hbase/data_migration.md'
        - Management: 'applications/hbase/management.md'
        - Observability: 'applications/hbase/observability.md'
        - Performance Tests: 'applications/hbase/performance_tests.md'
        - Security: 'applications/hbase/security.md'
  - 6 - Architecture:
      - Batch:
        - Introduction: 'architecture/batch/introduction.md' 
      - Ad Hoc:
        - Introduction: 'architecture/adhoc/introduction.md' 
        - Architecture: 'architecture/adhoc/architecture.md'         
      - Notebooks:
        - Introduction: 'architecture/notebooks/introduction.md'       
      - Datalake Storage:
        - Introduction: 'architecture/datalake_storage/introduction.md'         
    # - Hive: 'index.md'      
    # - Introduction: 'index.md'
  # - Performance:
  #   - Introduction: 'index.md'
  # - Reliability:
  #   - Introduction: 'index.md'
  # - Applications:
  #   - Spark: 'index.md'
  #   - Hive: 'index.md'
  #   - Hbase: 'index.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
